# Generated by Django 5.1.7 on 2025-09-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='posicion',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
